### DISCUSSION TITLE
Apply permissions to OOTB group and service user

### DISCUSSION THREAD

**Discussion by sn8083** [Netcentric/accesscontroltool#784] [Q&A]
Hi I need to apply permissions to OOTB workflow service user and workflow-users group.
question is should there be entries in group_config and user_config in yaml for OOTB groups/users.
or can i just add permissions in ace_config.

**Comment by kwin** [comment]
Please check out the documentation at https://github.com/Netcentric/accesscontroltool/blob/develop/docs/AdvancedFeatures.md#configure-permissions-for-built-in-users-or-groups-like-anonymous.

**Reply by sn8083** [reply]
hi @kwin 
as mentioned in the document i have used 
- global_config:
      defaultUnmanagedExternalIsMemberOfRegex: .*      
      defaultUnmanagedExternalMembersRegex: .*

and i am trying to apply permissions for an OOTB service user- workflow-service, getting NoGroupDefinedException_
_NoGroupDefinedException: Validation error while reading ACE definition nr.1 of authorizable workflow-service is not defined in group configuration_

**Comment by kwin** [comment]
> In those cases just list the built-in authorizable (user/group) in the YAML file (with the correct authorizable id) and leverage unmanagedAcePathsRegex as outlined below. No other properties need to be set on the authorizable as this is in fact not touched by the ACTool.

(https://github.com/Netcentric/accesscontroltool/blob/develop/docs/AdvancedFeatures.md#configure-permissions-for-built-in-users-or-groups-like-anonymous)

You still need to have the built-in group listed as stated above below `-group_config`.

**Reply by sn8083** [reply]
i have added both entries like below. 

```
-global_config:
   defaultUnmanagedExternalIsMemberOfRegex: .*
   defaultUnmanagedExternalMembersRegex: .*
- ace_config:
    - workflow-service:
      - path: /apps
        permission: allow
        privileges: jcr:read
 ```
