### ISSUE TITLE
rep:glob rule with empty quotes ("") is not working

### ISSUE THREAD

**Issue by chetanyajain** [Netcentric/accesscontroltool#115]
I have configured the below rule on a folder
```
- group_config:
    - cjain-admin:
       - name: 
         isMemberOf: 
         path: /home/groups/c

- ace_config:
    - cjain-admin:
       - path: /content/cj
         permission: allow
         actions:  
         privileges: jcr:read
         repGlob: ""
```

From JMX console when I perform groupBasedDump() I get the output in the following way (i.e. "" is missing):

```
- cjain-admin:

       - path: /content/cj
         permission: allow
         actions: 
         privileges: jcr:read
         restrictions:
           rep:glob: 
```

Also if I explicitly add "" and execute the yaml file, I do not get the same result (i.e. "" is ignored)

```
- cjain-admin:

       - path: /content/cj
         permission: allow
         actions: 
         privileges: jcr:read
         restrictions:
           rep:glob: ""
```
