### ISSUE TITLE
rep:glob with asterisk should be within single quotes

### ISSUE THREAD

**Issue by chetanyajain** [Netcentric/accesscontroltool#117]
In the documentation we have mentioned the below point for path:

> > If an asterisk is contained then the path has to be written inside single quotes ('...') since this symbol is a functional character in YAML.

The same rule should also apply even for rep:glob. After taking the dump when I was parsing the YAML file it throws an error 

```
while scanning an alias
  in "<unicode string>", line 26, column 22:
               rep:glob: */activities/*/sling:resourceType
                         ^
expected alphabetic or numeric character, but found '/'
  in "<unicode string>", line 26, column 23:
               rep:glob: */activities/*/sling:resourceType
                          ^
```

Here's the sample YAML file on which I was running the parser

```
- ace_config:

    - account-manager:

       - path: /content
         permission: allow
         actions: 
         privileges: jcr:read


       - path: /etc/security/accountmgr
         permission: allow
         actions: 
         privileges: jcr:read


    - activity-service:

       - path: /
         permission: allow
         actions: 
         privileges: rep:addProperties
         restrictions:
           rep:glob: */activities/*/sling:resourceType
```
