### ISSUE TITLE
Allow to define the order of ACEs 

### ISSUE THREAD

**Issue by ghenzler** [Netcentric/accesscontroltool#120]
In the context of restrictions [1], it would sometimes make sense to keep the order of ACEs as listed in config file (opposed to sort denies to the top).

[1]
https://jackrabbit.apache.org/oak/docs/security/authorization/restriction.html
https://sling.apache.org/documentation/bundles/sling-oak-restrictions.html

To implement, the following implementation approaches are conceivable:

1. Global Switch in `global_config` to turn off reordering completely 
   - Con: Violates our best practice to order denies to the top of the list. If it is only configurable globally, one part might be fixed but another (existing) part might break
2. New `ranking` property on every ACE (with deny having a smaller default ranking as allow)
    - Pro: Only effective locally 
    - Pro: Very flexible
    - Con: Duplicated information, there is a natural order in config file and a ranking that can be out of sync
    - Con: Hard to implement for the restriction dump if it is not desired to add a ranking to every ACE of the restriction dump (ranking should only be added if really necessary to not bloat the file and make it a good base to start working on the export as master)
    - Con: Gets complicated to understand and if multiple groups define ACEs for the same path

3. New `keepOrder` property
    - Pro: Only effective locally (default `false`)
    - Pro: Works naturally as if this is set, the deny is ordered in exactly the same way as the allows (the natural order as the ACEs appear in config file)
    - Pro: For the restriction dump this property can easily be set if an ACE deny entry is found that has preceding allows
    - Pro: Works reasonably well across same paths in different groups

=> Option 3 should be the best.

Example (this group gives editor access to `/content/myproj`, except to iframes:
```
- group-that-gives-access-with-restrictions:

       - path: /content/myproj
         permission: allow
         actions: read,acl_read,create,modify
         privileges:

       - path: /content/myproj
         permission: deny
         privileges: rep:write
         keepOrder: true # this ensures that the rule is NOT ordered to top and hence does not 
                         # make the action modify from rule above take precedence
         restrictions:
                  sling:resourceTypes:  myproj/iframe
```
