### ISSUE TITLE
AC Tool doesn't install modify action correctly

### ISSUE THREAD

**Issue by jochenkoschorke** [Netcentric/accesscontroltool#13]
The modify-cqAction doesn't get installed by the AC Tool. If e.g. a combination of read, modify and create is defined in a YAML configuration file, only read and create get installed in repository but not modify.

**Comment by ugocei** [comment]
I used the following configuration as a test:

```
- group_config:

    - groupA:

       - name: 
         isMemberOf: 
         path: /home/groups/g
         
- ace_config:

    - groupA:

       - path: /content/actool
         permission: allow
         actions: read
         repGlob: ""

       - path: /content/actool
         permission: allow
         actions: read,modify,create
```

And it installs two ACEs, as expected. One has the jcr:privilege and the other one has the following privileges:

```
jcr:addChildNodes, jcr:read, jcr:versionManagement, jcr:nodeTypeManagement, jcr:lockManagement, jcr:modifyProperties
```

Which I think are correct. If I only specify 'read,create' as actions, the resulting privileges are as follows:

```
jcr:addChildNodes, jcr:read, jcr:nodeTypeManagement
```

To me, this looks correct. If you think it isn't, please explain what is the expected outcome.
