### ISSUE TITLE
Support for repository level access control entries

### ISSUE THREAD

**Issue by josephrignanese** [Netcentric/accesscontroltool#137]
Currently it doesn't seem possible to create repository level access control entries. This is required to set some privileges like jcr:namespaceManagement.

**Comment by jochenkoschorke** [comment]
Hi, this should already be possible by defining the mentioned privilege in your ACE definition in your yaml file. Could you please add informations about the version of the Ac Tool you used, as well as your yaml configuration?

**Comment by ghenzler** [comment]
Just tested with the following example that worked fine (I used v1.9.1):
```
    - mygroup:

        - path: /etc/dashboards
          permission: allow
          privileges: jcr:namespaceManagement
```

**Comment by ghenzler** [comment]
@josephrignanese Please reopen this ticket if the problem remains (the given example should really work though).

**Comment by josephrignanese** [comment]
@ghenzler @jochenkoschorke, sorry I only just saw this activity.

For repository level permissions, they do not get applied to a specific path, but rather are applied to the repo and visible in /rep:repoPolicy

Even if I set the path to / in the yaml file the AC tool will create a rep:policy entry on the root path (expected behaviour IMO and desirable in many circumstances), so a mechanism would need to be created to allow for repository level permissions. Also tried using an empty path ("") but that just gave an error.

You can check if the jcr:namespaceManagement privilege is working by trying to create a new namespace via crx explorer.

And the way to view/modify repository level privileges in crxde is to go to the Access control tab and then click the "Repository" checkbox.

**Comment by josephrignanese** [comment]
I believe that repo level policies are controlled using the `null` path.

See http://jackrabbit.apache.org/oak/docs/security/accesscontrol/default.html

**Comment by ghenzler** [comment]
@josephrignanese This makes it clearer and hence there is work to do, reopening.

**Comment by ghenzler** [comment]
@josephrignanese What do you think would be the best/clearest syntax for this in the yaml?

```  
- mygroup:

        # Option 1 leaving it emtpy
        - path:  
          permission: allow
          privileges: jcr:namespaceManagement

        # Option 2 leaving out entire property
        - permission: allow  
          privileges: jcr:namespaceManagement

        # Option 3 have a clear constant string to mark it as repo level entry
        - path: REPOSITORY 
          permission: allow
          privileges: jcr:namespaceManagement

        # Option 4 introduce a new boolean property (if set to true, path must not be set)
        - isRepositoryLevelPermission: true  
          permission: allow
          privileges: jcr:namespaceManagement
```
