### ISSUE TITLE
Support setting ACEs for user ids

### ISSUE THREAD

**Issue by kwin** [Netcentric/accesscontroltool#141]
When setting an ACE to a principal id which is bound to a user and not a group, the ACTool will emit the following error

>  Validation error while reading ACE definition nr.1 of authorizable: `someuserid`is not defined in group confiiguration

The reason is that `AceBeanValidatorImpl#validateAuthorizableId(...)` is only checking if the ID is mentioned in the group definitions (not in the user definitions) in  https://github.com/Netcentric/accesscontroltool/blob/develop/accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/validators/impl/AceBeanValidatorImpl.java#L292.

Although this is violating the best practice to only assign ACEs to groups and not user, for some edge cases this still makes sense.

**Comment by mtstv** [comment]
As workaround for example for anonymous user I created another group, set rights for this group and assigned anonymous to this group.

**Comment by ghenzler** [comment]
Just tested with version 1.9.5 and it works totally fine with both system users and regular users: 

```
- user_config:

    - user-test-issue141:
        - name: "Test user for testing #141"
          password: "test"

    - systemuser-test-issue141:
        - name: "System user for testing #141"
          isSystemUser: true

- ace_config:

    - user-test-issue141:

        - path: /content/geometrixx
          permission: allow
          actions: read,acl_read
          repGlob:

    - systemuser-test-issue141:

        - path: /content/geometrixx
          permission: allow
          actions: read,acl_read
          repGlob:
```

**Comment by ghenzler** [comment]
@kwin must have been with an older version, please re-open if problem persists.

**Comment by harishkm2k** [comment]
In our case, we had to provide `anonymous` user to have access to ELB Health Check endpoint. So, we did this,
```
- ace_config: 
     - everyone:
            # ELB Health Check end point for Anonymous user
            - path: /content/regent
            permission: allow
            actions:
            privileges: jcr:read
```
