### ISSUE TITLE
Allow to set variables

### ISSUE THREAD

**Issue by ghenzler** [Netcentric/accesscontroltool#153]
In the context of #140 solution option 3 and to avoid duplication, it would be really good to be able to set global variables/constants as follows:

```
- group_config:

    - DEF ldapGroupTemplate="cn=PLACEHOLDER,ou=mydepart,ou=Groups,dc=comp,dc=com;IDPNAME"

    - aem-only-editor-group:
        - name: "AEM Role Editor"
          externalId: ${replace(ldapGroupTemplate, "PLACEHOLDER", "group-name")}

```
