### ISSUE TITLE
Defining Arrays / Lists rather than string objects

### ISSUE THREAD

**Issue by mittalkunal** [Netcentric/accesscontroltool#184]
Hi

Is it possible to have support for Defining variables which can have multiple values like Array / List.

We have a use case where we need to create groups and assign permissions for mutiple hierarchies of content but not all. What I was thinking was to define a variable at global level and use the same for creation of groups as well as assigning permissions. Something like below:

```
- DEF markets=[us,ca]

- group_config:

  - FOR market in ${markets}:

    - editors-${market}:
       - name: Editor for ${market}
         isMemberOf: 
         path: /home/groups/${market}

- ace_config:

  - FOR market in ${markets}:

    - editor-{market}:

      - path: /content/xyz/${market}
        permission: allow
        actions: read,modify,create,delete,acl_read,acl_edit,replicate
        repGlob: */jcr:content*
```

Secondly if - IF ${endsWith(site.name,'-master')}: can have an array as well so that we can use the if condition to work with various values rather than 1
