### ISSUE TITLE
Only first IF is executed inside FOR loop

### ISSUE THREAD

**Issue by inedoviesov1** [Netcentric/accesscontroltool#187]
If there are more than one `IF` statement inside the `FOR` loop then only first `IF` is executed.
Example config:

```
- group_config:

    - FOR siteRoot IN CHILDREN OF /content/geometrixx:

        IF ${siteRoot.name eq "en"}:

            - testgroup-for-en:

                - name: Test group for EN
                  isMemberOf: 
                  members: 
                  path: t

        IF ${siteRoot.name eq "fr"}:

            - testgroup-for-fr:

                - name: Test group for FR
                  isMemberOf: 
                  members: 
                  path: t
```

Expected result:
Groups "Test group for EN" and "Test group for FR" are created.

Actual result:
Only group "Test group for EN" is created.

Note: 
After changing the order another group is created. So only first IF works inside FOR loop.
