### ISSUE TITLE
Automatically create test users for configured runmodes

### ISSUE THREAD

**Issue by ghenzler** [Netcentric/accesscontroltool#208]
It is often required for to have exactly one test user per role to be able to test, but only on staging environments. This could be automatically generated when providing the following configuration:

```
- global_config:
      autoCreateTestUsers:
           createForGroupNamesRegEx: "myproj.*" # to select the groups test users should be created for
           prefix: "tu-"  # prefix is required
           path: /home/users/myproject-test-users
           password: "mypw"   # a generic pw for the test users, if left out defaults to user name
           skipForRunmodes: prod, production # can be given to skip for certain runmodes (prod, production is the default)
```
