### ISSUE TITLE
Do not check for return value of addMember() (Revert check from #275)

### ISSUE THREAD

**Issue by ghenzler** [Netcentric/accesscontroltool#283]
For unsaved authorizables [1] returns false, hence a check as introduced with #275 does not make sense.

[1] https://jackrabbit.apache.org/api/2.6/org/apache/jackrabbit/api/security/user/Group.html#addMember(org.apache.jackrabbit.api.security.user.Authorizable)

**Comment by ghenzler** [comment]
After some more tests it turns out that it is not unsaved authorizables, but rather only unsaved authorizables that previously existed in the system. To reproduce:

```
- obsolete_authorizables:
 # move the user config to here, run it, then paste the user config down to user_config again, run it to reproduce
- user_config:

    - testUserToBeCreated:
        - isMemberOf: testGroupToBeCreated
          password: 'test'
          path:  /home/users/test

- group_config:
    - testGroupToBeCreated:
        - path:  /home/groups/test
```
With 2.0.7, testUserToBeCreated will not be created if it was previously in the `obsolete_authorizables` section (this is a dev workflow that is sometimes used to reset authorizables). 

With 2.0.6 (and addMember() returning false), when checking afterwards the member `testUserToBeCreated` is still added correctly to `testGroupToBeCreated` even though  addMember()  returned false
