### ISSUE TITLE
nested Expression Language case not working

### ISSUE THREAD

**Issue by littlesnitch** [Netcentric/accesscontroltool#284]
I have a case where I want inside of a FOR loop decide with the help of an boolean IF check set a variable.
But at the moment this doesn't seem to work.

This is an example for that:
- ace_config:

    - for contentlevel1 in [ food1, food2 ]:

        - for contentlevel2 in [ juice1, juice2, juice3 ]:

            - IF ${contains(contentlevel1,"food1")}:
                - DEF ingredient="sugar"

                - ${contentlevel1}-${contentlevel2}:

                    - path: /content/${contentlevel1}/${contentlevel2}
                      permission: allow
                      actions: read,delete,modify,create
                      privileges:
                      repGlob:

                    - path: /etc/cloudservices/cc-cookiecontroller/${contentlevel1}-${contentlevel2}-${ingredient}config
                      permission: allow
                      actions: read,delete,modify,create
                      privileges:
                      repGlob:

Can you please help if this is possible?
Thank you.

**Comment by ghenzler** [comment]
Just tested with this example (easier since that way the value of `ingredient` can easily be checked in group profile:
```
- group_config:


   - for contentlevel1 in [ food1, food2, food3 ]:

       - IF ${contains(contentlevel1,"food1")}:
            - DEF ingredient="sugar"

            - testgroup-${contentlevel1}:
                - name: "Group ${contentlevel1}"
                  description: "ingredient = ${ingredient}"
                  path: /home/groups/test284/${contentlevel1}

       - IF ${contains(contentlevel1,"food2")}:
            - DEF ingredient="salt"

            - testgroup-${contentlevel1}:
                - name: "Group ${contentlevel1}"
                  description: "ingredient = ${ingredient}"
                  path: /home/groups/test284/${contentlevel1}

       - IF ${contains(contentlevel1,"food3")}:

            - testgroup-${contentlevel1}:
                - name: "Group ${contentlevel1}"
                  description: "ingredient = ${ingredient}"
                  path: /home/groups/test284/${contentlevel1}
```
It works correctly, for first user it is `sugar`, for second it is `salt`, for third it is empty (var not defined). This is because of the code at https://github.com/Netcentric/accesscontroltool/blob/2.0.8/accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/configreader/YamlMacroProcessorImpl.java#L202 that clones the map for a particular loop.
