### ISSUE TITLE
Allow to use new Oak restrictions in yaml files and add them to dumps

### ISSUE THREAD

**Issue by jochenkoschorke** [Netcentric/accesscontroltool#36]
Oak introduces new restrictions like rep:ntNames and rep:prefixes (all listed in https://jackrabbit.apache.org/oak/docs/security/accesscontrol/restriction.html). These should also appear in dumps generated by the AC Tool  in each ACE where set in repository. Also the tool should be able to create those restrictions.
In case the underlying repository is not Oak or not supporting that restriction we should throw an exception!

**Comment by ghenzler** [comment]
Restrictions are extensible (https://jackrabbit.apache.org/oak/docs/security/authorization/restriction.html#Pluggability) and the name must not follow any prefix (and most importantly not all restrictions necessarily have to match the pattern rep:* as the standard ones do, see e.g. https://issues.apache.org/jira/browse/SLING-5768 for a sling:resourceTypes restriction). 

Therefore the sub node "restrictions" shall be introduced as follows:
```
   - path: /content/myproj
          permission: allow
          actions: read,create,modify,delete
          restrictions:
             rep:ntNames: cq:Page 
```
