### ISSUE TITLE
Support for restrictions on properties using rep:itemNames

### ISSUE THREAD

**Issue by ompandeyy** [Netcentric/accesscontroltool#360]
As per the documentation on https://github.com/Netcentric/accesscontroltool/blob/00373ac2750ac49865c46c5fd6fa1e5a849b2ec1/docs/Configuration.md, we can configure restrictions for `rep:itemNames` but when we try this using below example snippet, it doesn't configure.

```
- path: /content/myproject/tenant/site
              permission: allow
              privileges: rep:write
              restrictions:
              rep:itemNames: 'cq:lastModified'
```

Please note that in the AC Tool documentation only nodeNames are mentioned for `rep:itemNames`  but it should work with the properties as well. http://jackrabbit.apache.org/oak/docs/security/authorization/restriction.html
