### ISSUE TITLE
The IF ${startsWith('xyzzy',item)}:  statement does not seem to work as expected

### ISSUE THREAD

**Issue by asaha90** [Netcentric/accesscontroltool#361]
@craghav please reopen if the described approach does not work for you

_Originally posted by @ghenzler in https://github.com/Netcentric/accesscontroltool/issues/342#issuecomment-456013112_

**Comment by asaha90** [comment]
I was using the same snippet as mentioned by @craghav earlier.  

- FOR item IN ${RUNMODES}:
        - IF ${startsWith('xyzzy',item)}: 
        - DEF variable = [something]

Irrespective of the if condition, the definition variable get updated every time.  It seems the if statement is not working.  Can anybody please help with a valid IF statement that can be used.

**Comment by ghenzler** [comment]
@asaha90 I think  the indentation is wrong in your example (in YAML that's very important!) - I tested a bit back and forth and the following sets the variable `testPath`  correctly according runmode (you get ACE entries for all three values of `testPath` for the typical runmodes of an author):

```
- user_config:

    - FOR item IN ${RUNMODES}:

        - test-service-user-${item}:
            - name: "Test User Runmode ${item}"
              path: /home/users/system/test
              isSystemUser: true

- ace_config:

    - DEF testPath="/content"

    - FOR item IN ${RUNMODES}:
        - IF ${startsWith('author',item)}: 
             - DEF testPath="/etc/dam"

        - IF ${item eq 'crx3'}: 
             - DEF testPath="/etc/designs"

        - test-service-user-${item}:
    
            - path: ${testPath}
              permission: allow
              actions: read
```
