### ISSUE TITLE
Undeclared variables are not detected while applying or deploying YAML 

### ISSUE THREAD

**Issue by leonardoderks** [Netcentric/accesscontroltool#362]
It would be good to have an exception when we use undeclared variables in a YAML file.
Example in the following code:

 ```
- DEF groups=[case1,case2,case3]
# Groups
 - group_config:
    - FOR group IN ${groups}:
        - appl-om-de-dev-example-${group}-pd:
            - name: appl-om-de-dev-example-${group}-pd
              isMemberOf: parent-role
              path: /home/groups/pages/example/${site}-default

# Permissions
 - ace_config:
    - FOR group IN ${groups}:
        - appl-om-de-dev-example-${group}-pd:
           - path: /content/pages/example/${site}
             permission: allow
             actions: read
```

The variable ${site} is not defined and instead of throwing an exception is replaced by an empty value.
