### ISSUE TITLE
Ignore trailing slashes for same path definitions

### ISSUE THREAD

**Issue by luckyluke80** [Netcentric/accesscontroltool#370]
The following configuration ignores the permissions for groupB and groupC and possibly all following group definitions with the same path.

```
- def groupPath="/home/groups/slashissue/fragments"

- group_config:

    - groupA:
      - path: ${groupPath}
  
    - groupB:
      - path: ${groupPath}

    - groupC:
      - path: ${groupPath}

- ace_config:

    - groupA:
        - path: /content/dam/we-retail/
          permission: allow
          actions: read

    - groupB:
        - path: /content/dam/we-retail
          permission: allow
          actions: read,modify,create,delete

    - groupC:
        - path: /content/dam/we-retail
          permission: allow
          actions: acl_read,replicate
```

It's currently not allowed to mix trailing slashes for the same path. The permissions are applied if no trailing slashes for the same path are defined or if all same path's have trailing slashes.
