### ISSUE TITLE
Recreating the 'everyone' group in a different location after changes in config.yaml

### ISSUE THREAD

**Issue by ichirital** [Netcentric/accesscontroltool#373]
This is **not** a Netcentric Bug, rather a configuration issues that is giving us some problem down the line and would like some feedback from the contributors of this project on any possible side-effects.

**Environment**:
* AEM 6.4 SP2
* Netcentric Access Control Tool 2.0.5
* Config.yaml with the below entry:
```
- group_config:

  - everyone:

    - name: 'everyone'
      memberOf:
      members:
      path: /home/groups/e/everyone
      unmanagedAcePathsRegex: /(?!apps/settings/notification/email/my-project).*
```

**Outcome**:
* the everyone group got renamed and moved to a new 'everyone' rep:AuthorizableFolder

**Problem**:
* this is causing us issues upon upgrade to AEM 6.5, as we also have ACS Commons dependency and version 4.x.x isn't expecting 'everyone' to be in that location

**Question**: I know that the way the 'everyone' group is being managed / ignored has changed since version 2.0.5, but I'd like to know if there have been any issues in the past that you are aware of when moving the 'everyone' group from its original location, either by changing the configuration of the YAML file to something like below (which will actually delete the group and recreate it) or by using cURL commands.

```
- group_config:

  - everyone:

    - name: 'everyone'
      memberOf:
      members:
      path: /home/groups/e
      unmanagedAcePathsRegex: /(?!apps/settings/notification/email/my-project).*
```

OR

```
# Move everyone group into parent folder
curl -u admin:admin -F":operation=move" -F":applyTo=/home/groups/e/everyone/yxrAA31pkJS0JKPR0gzZ" -F":dest=/home/groups/e/" http://localhost:4502/home

# Delete everyone folder
curl -u admin:admin -F :operation=delete http://localhost:4502/home/groups/e/everyone
```

Thank you
