### ISSUE TITLE
Usage of object in YAML file

### ISSUE THREAD

**Issue by brianovic** [Netcentric/accesscontroltool#425]
I tried to use a data structure which offers information for the sites which are created by the ACL-Tool as initial content. This means i am trying to create an array ob objects in YAML and looping that for group_config and ace_config. At the moment i only managed to use an array of string to create this sites: `- DEF sites=[playground, miniplayground]`
In future i also want to provide information like title and discription, so i like to have da data structure like this 
<pre><code>- sites:
  - name: playground
    title: Playground Area
    description: Playground can be used to try out some content creation

  - name: training
    title: Training Area
    description: The content for training workshops is located here </code></pre>
Unfortnately i did not managed to use this data structure in the ACL-Tool. I think object are not supported in ACL-Tool, is that true? If yes can you enhance this as a feature?

Thanks!

**Comment by kwin** [comment]
@brianovic Can you clarify what you want to achieve? You want to use complex objects as variables or somewhere else in the config (where?). Providing a yaml snippet which shows both definition and desired usage of this variable would help here a lot.

**Comment by ghenzler** [comment]
I think the closest you can get today to what you want (if understand correctly) is

```
- DEF sites=[playground/Playground Area/Playground can be used to try out some content creation, training/Training Area/The content for training workshops is located here ]

- group_config:

    - FOR site IN ${sites}:
        - DEF siteId=${split(site,'/')[0]}
        - DEF siteName=${split(site,'/')[1]}
        - DEF siteDesc=${split(site,'/')[2]}
        - testgroup-${siteId}:
            - name: "Test Group ${siteName}"
              description: ${siteDesc}
              members: anonymous
              path:  /home/groups/actooltestgroups
```
But really, why don't you just write the groups in the regular syntax? The following is a lot nicer to read:
```
- group_config:

        - testgroup-playground:
            - name: "Test Group Playground Area"
              description: "Playground can be used to try out some content creation"
              members: anonymous
              path:  /home/groups/actooltestgroups

        - testgroup-training:
            - name: "Test Group Training Area"
              description: "The content for training workshops is located here "
              members: anonymous
              path:  /home/groups/actooltestgroups
```
