### ISSUE TITLE
Dump contains duplicate ACEs in case no additional index definitions are installed

### ISSUE THREAD

**Issue by kwin** [Netcentric/accesscontroltool#444]
When downloading a dump from a plain AEM 6.5.4 via http://localhost:4502/mnt/overlay/netcentric/actool/content/overview.html/actool -> Download Dump it contains the following part

```
- community-group-administrators:

       - path: /
         permission: allow
         privileges: jcr:read


       - path: /home
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /content
         permission: allow
         privileges: jcr:read


       - path: /content
         permission: allow
         privileges: jcr:read


       - path: /content
         permission: allow
         privileges: jcr:read


       - path: /content
         permission: allow
         privileges: jcr:read


       - path: /content
         permission: allow
         privileges: jcr:read


       - path: /content
         permission: allow
         privileges: jcr:read


       - path: /content
         permission: allow
         privileges: jcr:read


       - path: /content
         permission: allow
         privileges: jcr:read


       - path: /content
         permission: allow
         privileges: jcr:read


       - path: /content
         permission: allow
         privileges: jcr:read


       - path: /content
         permission: allow
         privileges: jcr:read


       - path: /content
         permission: allow
         privileges: jcr:read


       - path: /content
         permission: allow
         privileges: jcr:read


       - path: /content
         permission: allow
         privileges: jcr:read


       - path: /content
         permission: allow
         privileges: jcr:read


       - path: /content
         permission: allow
         privileges: jcr:read

...
```

I.e. There are a lot of duplicate ACEs in the dump for version  2.5.1. To me it seems that instead of the direct ACEs also transitive ones are emitted (i.e. those inherited from other groups). That is obviously wrong.

**Comment by sumrob** [comment]
FYI, I am seeing the same thing.

**Comment by ghenzler** [comment]
So I just checked the locally with version AC Tool 2.5.2 (AEM 6.5.4.0) and path `/mnt/overlay/netcentric/actool/content/overview/content/items/actoolpanel.html/dump.yaml` and the  part for the group `community-group-administrators` looks ok for me:

```
    - community-group-administrators:

       - path: /
         permission: allow
         privileges: jcr:read


       - path: /home
         permission: allow
         privileges: jcr:read


       - path: /apps
         permission: allow
         privileges: jcr:read


       - path: /content
         permission: allow
         privileges: jcr:read


       - path: /libs
         permission: allow
         privileges: jcr:read
```
@kwin @sumrob So the issue mentioned 2.5.1 as version, I don't think this is the root cause (no changes in respect to this between 2.5.1/2.5.2). But let's try to find differences: The instance I tested with does not use AEM communities, maybe this somehow happens with a state that communities produces - can you investigate a bit in CRXDE to find differences between groups where you don't have duplication in the export and groups like `community-group-administrators` that have duplication?

**Comment by kwin** [comment]
I tried again on the instance with 2.5.2 and I still see the issue. I even see duplications for the administrators group

```
  - administrators:

       - path: /apps/netcentric/actool/content/overview
         permission: allow
         privileges: jcr:read


       - path: /apps/cq/core/content/nav/tools/security/actool
         permission: allow
         privileges: jcr:read


       - path: /apps/cq/core/content/nav/tools/security/actool
         permission: allow
         privileges: jcr:read


       - path: /apps/netcentric/actool/content/overview
         permission: allow
         privileges: jcr:read


       - path: /apps/netcentric/actool/content/overview
         permission: allow
         privileges: jcr:read


       - path: /apps/cq/core/content/nav/tools/security/actool
         permission: allow
         privileges: jcr:read

```

With CRXDE the access control policies on path `/apps/cq/core/content/nav/tools/security/actool` look like this

<img width="772" alt="Screenshot 2020-03-27 at 17 13 55" src="https://user-images.githubusercontent.com/185025/77776575-7fac9c00-704e-11ea-857f-c39d9d98f503.png">


The same duplications can be observed via JMX for both `groupBasedDump` and `pathBasedDump`.
