### ISSUE TITLE
Variables in for-loops don't support ':' character

### ISSUE THREAD

**Issue by jgorgolewski** [Netcentric/accesscontroltool#452]
You cannot use ':' (colon) characters in for loops. It's similar issue to one reported in #14 and #330

```
private final Pattern forLoopPattern = Pattern.compile(
            "for +(\\w+)( +with +content)? +in +(?:\\[([,/\\s\\w\\-\\.]+)\\]|children +of +([^\\s]+)|(\\$\\{[^\\}]+\\}))",
            Pattern.CASE_INSENSITIVE);
```

should be probably extended to:

```
private final Pattern forLoopPattern = Pattern.compile(
            "for +(\\w+)( +with +content)? +in +(?:\\[([:,/\\s\\w\\-\\.]+)\\]|children +of +([^\\s]+)|(\\$\\{[^\\}]+\\}))",
            Pattern.CASE_INSENSITIVE);
```

Example use case is especially viable after move of /etc/tags to /content/cq:tags
```
- FOR path IN [ /content/project1, /content/cq:tags/project1a, /content/cq:tags/project1b ]:
  - project1-authors:
    - path:  {path}
      permission: allow
      actions: read,write
```
