### ISSUE TITLE
Allow to set ACEs for not yet existing nodes

### ISSUE THREAD

**Issue by kwin** [Netcentric/accesscontroltool#46]
In some cases ACEs need to be set, before the related content nodes do actually exist. Right now those ACEs are just skipped.

Possible solutions

1. Principal-based ACLs (http://wiki.apache.org/jackrabbit/AccessControl#Principal-based_ACLs), but they don't seem to be supported with Oak (https://issues.apache.org/jira/browse/OAK-3627)
2. Create the according content nodes if they don't exist yet (with a predefined template)
   * copying over nodes that exist in the JCR at a "template location" (e.g. creating the structure in /etc/actool/contenttemplate and copying nodes from there to the real structure by cutting out the path /etc/actool/contenttemplate) 
   * allow to specify a default content structure in a root element of the yaml config, e.g. initial_content
   * allow to specify a default content structure per path defined in ace_config section (as property "initialContent" of the ACE Entry itself

**Comment by ghenzler** [comment]
@kwin Considering that 1) is currently not supported by Oak, and 2) has the advantage that often root node structures have to be created anyway (if it is not the ACTool, then some other means have to be used, authors rarely create the base tenant structure from scratch) I vote for 2). 

Regarding the options for 2) Since for install hooks, the content contained in a AC Tool config packages is not yet available via the JCR API we would have to implement this twice (once in JCR API, once in Vault API), that's why I would provide the content structure in yaml in a root element "initial_content"

**Comment by kwin** [comment]
Do we really need the initial structure? FileVault automatically creates `nt:folder` nodes for any necessary parent nodes which do not exist yet. The maven-sling-plugin only allows to define nodetypes (https://issues.apache.org/jira/browse/SLING-3540) and defaults to `sling:Folder`. What is your use case of providing a whole content structure (including properties)?

**Comment by ghenzler** [comment]
@kwin we need cq:Page and jcr:content[cq:PageContent] with properties sling:resourceType and cq:template at least (this is both true for site root pages in /content and cloud config structure elements).

**Comment by ghenzler** [comment]
Having had a go at the implementation I would not suggest the last option from the ticket description: Instead of creating a new root element "initial_content" it is better to define a property "initialContent" directly at the ACE itself. Yaml allows to provide multiline string properties with "|" - this can be used to specify DocView Xml nicely inline. If used in for loops that way the token can be used in the initial content as well (e.g. for a jcr:title attribute). 

An example for initial content:
```yaml
        - path:  /etc/designs/bma2
          initialContent: |
               <bma2 jcr:primaryType="cq:Page">
                 <jcr:content jcr:primaryType="cq:PageContent" 
                              sling:resourceType="wcm/core/components/designer" 
                              cq:template="/libs/wcm/core/templates/designpage"/>
               </bma2>
          permission: allow
          actions: delete,replicate
          privileges:
          repGlob: 
```
