### ISSUE TITLE
Ensure the JMX purge authorizable actions never purge system groups/users

### ISSUE THREAD

**Issue by ghenzler** [Netcentric/accesscontroltool#535]
At the moment the fragment [1] works to set an ACL for the group everyone for applying 

The JMX methods to purge authorizables (e.g. `purgeAllAuthorizablesFromConfiguration()`) should properly deal with `everyone` and `unmanagedAcePathsRegex` settings

[1]
```
- group_config:
    - everyone:
        - unmanagedAcePathsRegex: /(?!apps/myproj/login).*

- ace_config:

    - everyone:
        - path: /apps/myproj/login
          permission: allow
          privileges: jcr:read

```
