### ISSUE TITLE
Fail for yaml lists with more than one item underneath authorizable config

### ISSUE THREAD

**Issue by ghenzler** [Netcentric/accesscontroltool#538]
The following config should fail:
```
- group_config:

    - fragment-xyz-editor:
        - path: /home/groups/test
        # only one item allowed underneath group name, the hyphen is wrong here
        - isMemberOf:
            - fragment-xyz
```
