### ISSUE TITLE
[Documentation] group key and externalId must "match" for groups that are synched from IMS, or else members can no longer login

### ISSUE THREAD

**Issue by pahupe** [Netcentric/accesscontroltool#595]
Not sure if I should directly update the documentation, therefore I submit this change as an issue:

On page https://github.com/Netcentric/accesscontroltool/blob/develop/docs/Configuration.md#configuration-of-groups > section "Configuration of groups", it should be noted that for groups that are synched from an external source (here: Adobe IMS), the authorizableId (the key) should "match" the externalId (without the ;suffix), or else the group synchronisation (performed on login) will fail and as a consequence, group members won't be able to login to AEM anymore.

Example for group synched from Admin Console / IMS: 
```
- group_config:

    - groupname-in-adminconsole:
        - name: displayname
          description: “Description"
          isMemberOf: contributor
          externalId: "groupname-in-adminconsole;ims"
```
