### ISSUE TITLE
Is it possible to use initialContent to write a multi / array property

### ISSUE THREAD

**Issue by LucaNerlich** [Netcentric/accesscontroltool#654]
Hi, is it possible, to set multi value properties inside initialContent?

Ive got this variable map:

```yaml
      - DEF useCaseTemplateMap=:
          crm:
            - /conf/myapp/settings/wcm/templates/c4c-fragment
          feedback:
            - /conf/myapp/settings/wcm/templates/c4c-fragment
            - /conf/myapp/settings/wcm/templates/c4c-feedback-xf
```

and im trying to set both values from feedback inside initialContent

```yaml
                    - path: ${xfRootPath}/${brand}/${region}/feedback
                      initialContent: |
                        <jcr:root jcr:primaryType="sling:OrderedFolder" jcr:title="feedback" cq:allowedTemplates="[${useCaseTemplateMap['feedback']}]">
                        </jcr:root>
```
Using 'feedback' here (its a variable in my code), Id expect it to write both values from the map[feedback]. However, no values get written. A single value works fine, when removing the square brackets though.
