### ISSUE TITLE
Allow to set profile and preferences data for authorizables

### ISSUE THREAD

**Issue by ghenzler** [Netcentric/accesscontroltool#71]
Setting and updating user properties is quite limited ATM (#69 addresses some of the issues). A generic approach to set profile/preferences data would be nice, especially for test users (we should use something like profileContent and preferencesContent rather then direct properties on the authorizable config node because with AEM 6, the user profile has many more properties as in CQ 5.x).

**Comment by carlosmorenoin** [comment]
In our use case what we needed was adding profile properties to some test groups and to some test users. The idea is something like this:
 ```
- testuser1:
                 - path: '/home/users/app'
                   password: xx
                   isMemberOf: group1
                   description: test user1
                   profile:
                                - propertyName1: value 1
                                  propertyName2: value 2 
```
where the properties have custom names. And the same for groups.
